### ISSUE TITLE
Crash: Error inflating Nointernet dialogue 

### ISSUE THREAD

**Issue by pateelhs** [appwise-labs/NoInternetDialog#3]
android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class <unknown>
                                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                              at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
                                                                                              at android.app.Dialog.setContentView(Dialog.java:512)
                                                                                              at am.appwise.components.ni.NoInternetDialog.onCreate(NoInternetDialog.java:163)
                                                                                              at android.app.Dialog.dispatchOnCreate(Dialog.java:394)

**Comment by robertlevonyan** [comment]
Hi, can you share your code?
