### ISSUE TITLE
.InflateException: Binary XML file line #23:

### ISSUE THREAD

**Issue by Addynt** [appwise-labs/NoInternetDialog#36]
My target SDK version: 28

 android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)
        at android.app.Dialog.setContentView(Dialog.java:557)
        at am.appwise.components.ni.NoInternetDialog.onCreate(NoInternetDialog.java:198)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
        at android.app.Dialog.show(Dialog.java:302)
        at am.appwise.components.ni.NoInternetDialog.show(NoInternetDialog.java:578)
        at am.appwise.components.ni.NoInternetDialog$9.hasActiveConnection(NoInternetDialog.java:588)
        at am.appwise.components.ni.Ping.onPostExecute(Ping.java:22)
        at am.appwise.components.ni.Ping.onPostExecute(Ping.java:10)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0200fd a=-1}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:946)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
        at android.view.View.<init>(View.java:5010)
        at android.widget.ImageView.<init>(ImageView.java:177)
        at android.widget.ImageView.<init>(ImageView.java:172)
        at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
        at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420) 
        at android.app.Dialog.setContentView(Dialog.java:557) 
        at am.appwise.components.ni.NoInternetDialog.onCreate(NoInternetDialog.java:198) 
        at android.app.Dialog.dispatchOnCreate(Dialog.java:407) 
        at android.app.Dialog.show(Dialog.java:302) 
        at am.appwise.components.ni.NoInternetDialog.show(NoInternetDialog.java:578) 
        at am.appwise.components.ni.NoInternetDialog$9.hasActiveConnection(NoInternetDialog.java:588) 
        at am.appwise.components.ni.Ping.onPostExecute(Ping.java:22) 
        at am.appwise.components.ni.Ping.onPostExecute(Ping.java:10) 
        at android.os.AsyncTask.finish(AsyncTask.java:695) 
        at android.os.AsyncTask.access$600(AsyncTask.java:180) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/Process: Sending signal. PID: 24895 SIG: 9
Application terminated.

**Comment by kshitij-99** [comment]
so. no solution then ?

**Comment by aubryll** [comment]
I had the same problem, my solution was to dig into the lib, get the layout, change it to android x, use the same theme as my app theme and initialize the dialog using activity or fragment context and not the application context and it worked. Remember do not use app context.

**Comment by ImaginativeShohag** [comment]
You can try this similar library: https://github.com/ImaginativeShohag/Oops-No-Internet
