### ISSUE TITLE
Inflate Exception

### ISSUE THREAD

**Issue by jeremy-jamez** [appwise-labs/NoInternetDialog#8]
Receiving this error when I turn off wifi. The implementation is set in an Application Class. 
```
android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>
                                                                Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>
                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412)
                                                                    at android.app.Dialog.setContentView(Dialog.java:519)
                                                                    at am.appwise.components.ni.NoInternetDialog.onCreate(NoInternetDialog.java:192)
                                                                    at android.app.Dialog.dispatchOnCreate(Dialog.java:402)
                                                                    at android.app.Dialog.show(Dialog.java:301)
                                                                    at am.appwise.components.ni.NoInternetDialog.show(NoInternetDialog.java:566)
                                                                    at am.appwise.components.ni.NoInternetDialog$9.hasActiveConnection(NoInternetDialog.java:576)
                                                                    at am.appwise.components.ni.Ping.onPostExecute(Ping.java:22)
                                                                    at am.appwise.components.ni.Ping.onPostExecute(Ping.java:10)
                                                                    at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                    at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                                 Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0402d9 a=-1}
                                                                    at android.content.res.TypedArray.getDrawable(TypedArray.java:925)
                                                                    at android.view.View.<init>(View.java:4202)
                                                                    at android.widget.ImageView.<init>(ImageView.java:155)
                                                                    at android.widget.ImageView.<init>(ImageView.java:150)
                                                                    at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
                                                                    at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
                                                                    at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412) 
                                                                    at android.app.Dialog.setContentView(Dialog.java:519) 
                                                                    at am.appwise.components.ni.NoInternetDialog.onCreate(NoInternetDialog.java:192) 
                                                                    at android.app.Dialog.dispatchOnCreate(Dialog.java:402) 
                                                                    at android.app.Dialog.show(Dialog.java:301) 
                                                                    at am.appwise.components.ni.NoInternetDialog.show(NoInternetDialog.java:566) 
                                                                    at am.appwise.components.ni.NoInternetDialog$9.hasActiveConnection(NoInternetDialog.java:576) 
                                                                    at am.appwise.components.ni.Ping.onPostExecute(Ping.java:22) 
                                                                    at am.appwise.components.ni.Ping.onPostExecute(Ping.java:10) 
                                                                    at android.os.AsyncTask.finish(AsyncTask.java:667) 
                                                                    at android.os.AsyncTask.-wrap1(AsyncTask.java) 
                                                                    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6236) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
```

**Application Class:** 
```
@Override
    public void onCreate() {
        AppCompatDelegate.setDefaultNightMode(
                AppCompatDelegate.MODE_NIGHT_AUTO);
        super.onCreate();

        new NoInternetDialog.Builder(this)
                .setButtonColor(R.color.colorPrimary)
                //.setBgGradientEnd(getResources().getColor(R.color.colorPrimaryDark))
                .build();
}
```

**Comment by jeremy-jamez** [comment]
If I put in the main activity then it is displayed but what if i only want it to be displayed only once when the app is opened or connection is suddenly lost while on any screen

**Comment by robertlevonyan** [comment]
Once you instantiate the dialog, it will always pop when you lost the Internet connection, and dissapear when the connection is back. If you close the dialog and want to open it again you can call showDialog() method, but this will work only when you have no connection

**Comment by jeremy-jamez** [comment]
Yes I get that but let's say I have 5 different activities, with the first
activity being main. If I implement the dialog in the main activity and the
internet goes away while I'm on the third or fourth activity, the dialog
won't display unless I go back to the main activity. I want to avoid
implementing the dialog for each and every activity and just have it in my
application class which would enable the dialog throughout the entire app
instead of a single activity.
If it's not possible then it's fine, the dialog itself is not really a
necessity for me, just thought it would look cool

**Comment by robertlevonyan** [comment]
Actually you can have a BaseActivity as a parent for all your activities and add implementation on it

**Comment by VinceGee** [comment]
Did you get this to work? I'm facing the same problem:

FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:419)
        at android.app.Dialog.setContentView(Dialog.java:528)
        at am.appwise.components.ni.NoInternetDialog.onCreate(NoInternetDialog.java:198)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:403)
        at android.app.Dialog.show(Dialog.java:302)
        at am.appwise.components.ni.NoInternetDialog.show(NoInternetDialog.java:578)
        at am.appwise.components.ni.NoInternetDialog$9.hasActiveConnection(NoInternetDialog.java:588)
        at am.appwise.components.ni.Ping.onPostExecute(Ping.java:22)
        at am.appwise.components.ni.Ping.onPostExecute(Ping.java:10)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301d0 a=-1}

compileSdkVersion 28, targetSdkVersion 28, other dependencies are running 28.0.0

**Comment by Addynt** [comment]
i am also facing same problem.. Did u got the solution
Process: com.example.nointernetexamp, PID: 24895
    android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
targetSdkVersion: 28
